name: Copy Databases from Another Repo

on:
  workflow_dispatch:

jobs:
  copy-databases:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Current Repo
      uses: actions/checkout@v3
      with:
        path: current_repo

    - name: Checkout Source Repo (stocks_prediction_rnn_v2)
      uses: actions/checkout@v3
      with:
        repository: chiragpalan/stocks_prediction_rnn_v2
        path: source_repo
        token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

    - name: Copy Databases
      run: |
        mkdir -p current_repo/databases
        cp source_repo/nifty50_data_v1.db current_repo/databases/
        cp source_repo/predictions/predictions.db current_repo/databases/

    - name: Push Changes to Current Repo
      run: |
        cd current_repo
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add databases/
        git commit -m "Copied databases from stocks_prediction_rnn_v2"
        git push
