name: Copy Database Files

on:
  workflow_dispatch:

jobs:
  copy-files:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Text Classification Repo
      uses: actions/checkout@v2
      with:
        repository: chiragpalan/text_classification
        path: text_classification

    - name: Checkout Stocks Predictions RNN V2 Repo
      uses: actions/checkout@v2
      with:
        repository: chiragpalan/stocks_predictions_rnn_v2
        path: stocks_predictions_rnn_v2
        token: ${{ secrets.PAT }}

    - name: Copy Database Files
      run: |
        cp stocks_predictions_rnn_v2/path/to/nifty50_data_v1.db text_classification/databases/
        cp stocks_predictions_rnn_v2/predictions/predictions.db text_classification/databases/

    - name: Commit and Push Changes
      run: |
        cd text_classification
        git config --global user.email "your-email@example.com"
        git config --global user.name "your-username"
        git add databases/nifty50_data_v1.db databases/predictions.db
        git commit -m "Copy database files from stocks_predictions_rnn_v2"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.PAT }}
