name: Copy Databases Workflow

on:
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  copy_databases:
    runs-on: ubuntu-latest

    steps:
    # Checkout the target repository
    - name: Checkout source repository
      uses: actions/checkout@v3
      with:
        repository: chiragpalan/stock_prediction_rnn_v2
        token: ${{ secrets.GENERATE_CHARTS }} # Ensure the token is set with proper permissions
        path: source_repo
        ref: main # Replace 'main' with the actual default branch if it's different

    # Checkout the destination repository
    - name: Checkout destination repository
      uses: actions/checkout@v3
      with:
        repository: chiragpalan/text_classification
        token: ${{ secrets.GENERATE_CHARTS }}
        path: destination_repo
        ref: main # Replace 'main' with the actual default branch if it's different

    # Copy databases from source to destination
    - name: Copy Databases
      run: |
        # Ensure destination folder exists
        mkdir -p destination_repo/databases
        
        # Copy databases
        cp -r source_repo/nifty50_data_v1.db destination_repo/databases/
        cp -r source_repo/predictions/predictions.db destination_repo/databases/

    # Commit and push changes to the destination repository
    - name: Commit and Push Changes
      run: |
        cd destination_repo
        
        # Configure git
        git config --global user.name "chiragpalan"
        git config --global user.email "your-email@example.com" # Replace with your GitHub email
        
        # Commit changes
        git add databases/
        git commit -m "Copied databases from stock_prediction_rnn_v2 to text_classification"

        # Push changes
        git push origin main # Ensure the branch matches the destination repository's default branch
