name: Copy Databases and Generate Charts

on:
  workflow_dispatch:

jobs:
  copy-databases-and-generate-charts:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Current Repo
      uses: actions/checkout@v3
      with:
        path: current_repo

    - name: Checkout Source Repo (stocks_prediction_rnn_v2)
      uses: actions/checkout@v3
      with:
        repository: chiragpalan/stocks_prediction_rnn_v2
        path: source_repo
        token: ${{ secrets['generate charts'] }}

    - name: Copy Databases
      run: |
        mkdir -p current_repo/databases
        cp source_repo/nifty50_data_v1.db current_repo/databases/
        cp source_repo/predictions/predictions.db current_repo/databases/

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r current_repo/requirements.txt

    - name: Generate Candlestick Charts
      run: |
        python current_repo/generate_chart.py

    - name: Push Generated Charts to GitHub Pages
      run: |
        cd current_repo
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add .
        git commit -m "Generated candlestick charts"
        git push
