name: Copy Databases

on:
  workflow_dispatch:

jobs:
  copy-databases:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the text_classification repository
      - name: Checkout text_classification repository
        uses: actions/checkout@v3

      # Step 2: Checkout the stocks_prediction_rnn_v2 repository
      - name: Checkout stocks_prediction_rnn_v2 repository
        uses: actions/checkout@v3
        with:
          repository: chiragpalan/stocks_prediction_rnn_v2
          path: source_repo
          token: ${{ secrets.GENERATE_CHARTS }}

      # Step 3: Copy the databases from the source repository to the target location
      - name: Copy databases
        run: |
          mkdir -p databases
          cp source_repo/nifty50_data_v1.db databases/
          cp source_repo/predictions/predictions.db databases/

      # Step 4: Push the copied databases back to the text_classification repository
      - name: Push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add databases/nifty50_data_v1.db databases/predictions.db
          git commit -m "Add databases from stocks_prediction_rnn_v2"
          git push
