name: Generate Candlestick Chart

on:
  push:
    branches:
      - main

jobs:
  generate-chart:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Clone Private Repository
        run: git clone https://${{ secrets.GH_PAT }}@github.com/chiragpalan/stocks_prediction_rnn_v2.git

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas plotly requests

      - name: Run Script to Generate Chart
        run: python generate_chart.py
