name: Generate Candlestick Charts

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  generate-charts:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Copy databases from the source repository
      - name: Copy Databases
        run: |
          mkdir -p databases
          curl -L -o databases/nifty50_data_v1.db https://github.com/chiragpalan/stocks_prediction_rnn_v2/raw/main/databases/nifty50_data_v1.db
          curl -L -o databases/predictions.db https://github.com/chiragpalan/stocks_prediction_rnn_v2/raw/main/databases/predictions.db

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      # Install dependencies
      - name: Install Dependencies
        run: pip install pandas plotly

      # Run the Python script
      - name: Generate Charts
        run: python generate_chart.py

      # Deploy charts to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./charts
