name: Run Python Script

on:
  workflow_dispatch:  # Triggered by the refresh button

jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas plotly

    - name: Run Python script
      run: python generate_chart.py
